name = "ThreeHalf"
uuid = "39784460-17a6-42af-a8ad-986ad112d889"
authors = ["Sam Scholten <samcaspar@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
